# Project: Beginner1.1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Cpp_B1.1.o
LINKOBJ  = Cpp_B1.1.o
LIBS     = -L"D:/Dev-cpp/MinGW64/lib" -L"D:/Dev-cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Dev-cpp/MinGW64/include" -I"D:/Dev-cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Dev-cpp/MinGW64/include" -I"D:/Dev-cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Dev-cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Beginner1.1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Cpp_B1.1.o: Cpp_B1.1.cpp
	$(CPP) -c Cpp_B1.1.cpp -o Cpp_B1.1.o $(CXXFLAGS)
